### ISSUE TITLE
wine-staging package is broken

### ISSUE THREAD

**Issue by yoshi314** [backbone/Overlay#1]
From the build log : 
- Applying the unofficial Wine-Staging patchset which is unsupported
- by Wine developers. Please don't report bugs to Wine bugzilla
- unless you can reproduce them with USE=-staging
- Running Wine-Staging patch installer ...
- Applying 0001-opencl-Avoid-deprecation-warning-for-OpenCL-1.2-APIs.patch ...
- Failed Patch: 0001-opencl-Avoid-deprecation-warning-for-OpenCL-1.2-APIs.patch !
-  ( /mnt/storage/tmp/app-emulation-wine-1.7.55/work/wine-staging-1.7.51/patches/opencl-Deprecation/0001-opencl-Avoid-deprecation-warning-for-OpenCL-1.2-APIs.patch )
- 
- Include in your bugreport the contents of:
- 
-   /mnt/storage/tmp/app-emulation-wine-1.7.55/temp//0001-opencl-Avoid-deprecation-warning-for-OpenCL-1.2-APIs.patch.out

**Comment by backbone** [comment]
Thanks, I have used without "staging" flag. Now the ebuild removed from my overlay. Official portage tree has new 1.7.55 ebuild.
